In [1]:
import cv2 as cv
    
filename = "/Users/rawassizadeh/EVERYTHING/Work/TEACHING/CS 688_WebAnalyticsMining/toGithub/Session 6/funny-chicken.png"
img = cv.imread(filename)
print(img)
print("-------------")
hog = cv.HOGDescriptor()
h = hog.compute(img)
print(h)

[[[174 139  66]
  [174 139  66]
  [180 133 108]
  ...
  [204 137  64]
  [204 137  64]
  [204 137  64]]

 [[174 139  66]
  [180 133 108]
  [180 133 108]
  ...
  [204 137  64]
  [180 152  73]
  [204 137  64]]

 [[180 133 108]
  [213 153  84]
  [209 160  97]
  ...
  [204 137  64]
  [204 137  64]
  [204 137  64]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
-------------
[[0.20017219]
 [0.11096483]
 [0.22341101]
 ...
 [0.        ]
 [0.        ]
 [0.        ]]


In [2]:
import cv2 
import numpy as np

img = cv2.imread("/Users/rawassizadeh/EVERYTHING/Work/TEACHING/CS 688_WebAnalyticsMining/toGithub/Session 6/funny-chickenR.png")
gray= cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


sift = cv2.xfeatures2d.SIFT_create()
kp = sift.detect(gray,None)
img = cv2.drawKeypoints(gray,kp, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imwrite("/Users/rawassizadeh/EVERYTHING/Work/TEACHING/CS 688_WebAnalyticsMining/toGithub/Session 6/funny-chicken-siftedR.png",img)

True