In [1]:
import numpy as np
import tensorly as tl

import numpy as np
import tensorly as tl
tensor = tl.tensor(np.arange(60).reshape((3, 4, 5))) # 60 = 3 x4 x5
original_shape = tensor.shape

print('* original tensor:\n{}'.format(tensor))
print('original shape:')
print(original_shape)


* original tensor:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
original shape:
(3, 4, 5)


In [2]:

from tensorly import unfold
from tensorly import fold


mode1_t2 = unfold(tensor, 0) # mode-1 unfolding = convert a tensor into a vector
print('* unfolder (mode-1) tensor:\n{}'.format(mode1_t2))

mode2_t2 = unfold(tensor, 1) # mode-2 unfolding
print('* unfolder (mode-2) tensor:\n{}'.format(mode2_t2))

mode3_t2 = unfold(tensor, 2) # mode-3 unfolding
print('* unfolder (mode-3) tensor:\n{}'.format(mode3_t2))

torig = fold(mode3_t2, 2, original_shape) # 2 is used to specify the mode.
print('* again original tensor:\n{}'.format(torig))


* unfolder (mode-1) tensor:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]]
* unfolder (mode-2) tensor:
[[ 0  1  2  3  4 20 21 22 23 24 40 41 42 43 44]
 [ 5  6  7  8  9 25 26 27 28 29 45 46 47 48 49]
 [10 11 12 13 14 30 31 32 33 34 50 51 52 53 54]
 [15 16 17 18 19 35 36 37 38 39 55 56 57 58 59]]
* unfolder (mode-3) tensor:
[[ 0  5 10 15 20 25 30 35 40 45 50 55]
 [ 1  6 11 16 21 26 31 36 41 46 51 56]
 [ 2  7 12 17 22 27 32 37 42 47 52 57]
 [ 3  8 13 18 23 28 33 38 43 48 53 58]
 [ 4  9 14 19 24 29 34 39 44 49 54 59]]
* again original tensor:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [3]:
#------CANDECOP-PARAFAC decomposition ------
from tensorly.decomposition import parafac

print(mode1_t2)
print("-----------PARAFAC RANK 3-----------")
factors = parafac(mode1_t2, rank=3)
#len(factors)
print(tl.cp_to_tensor(factors))

print("-----------PARAFAC RANK 5-----------")
factors = parafac(mode2_t2, rank=5)
#len(factors)
print(tl.cp_to_tensor(factors))


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]]
-----------PARAFAC RANK 3-----------
[[-6.81036801e-12  1.00000000e+00  2.00000000e+00  3.00000000e+00
   4.00000000e+00  5.00000000e+00  6.00000000e+00  7.00000000e+00
   8.00000000e+00  9.00000000e+00  1.00000000e+01  1.10000000e+01
   1.20000000e+01  1.30000000e+01  1.40000000e+01  1.50000000e+01
   1.60000000e+01  1.70000000e+01  1.80000000e+01  1.90000000e+01]
 [ 2.00000000e+01  2.10000000e+01  2.20000000e+01  2.30000000e+01
   2.40000000e+01  2.50000000e+01  2.60000000e+01  2.70000000e+01
   2.80000000e+01  2.90000000e+01  3.00000000e+01  3.10000000e+01
   3.20000000e+01  3.30000000e+01  3.40000000e+01  3.50000000e+01
   3.60000000e+01  3.70000000e+01  3.80000000e+01  3.90000000e+01]
 [ 4.00000000e+01  4.10000000e+01  4.20000000e+01  4.30000000e+01
   4.40000000e+01  4.50000000e+01  4.60000000

In [4]:
#------Tucker decomposition ------
from tensorly.decomposition import tucker
from tensorly import tucker_to_tensor

core, factors = tucker(mode1_t2, rank=[3, 4, 5])

print('core:')
print(core)

print('core.shape:')
core.shape

print('factors:')
print(factors)


core:
[[ 2.64106761e+02  8.92619692e-15 -1.70967917e-14  1.17511038e-14]
 [ 3.90132225e-14 -2.13920262e+01 -2.49074531e-16 -1.17630347e-15]
 [ 3.21297551e-14  1.34659552e-14  4.74451397e-15  7.84142377e-31]]
core.shape:
factors:
[array([[-0.1736132 ,  0.89620968,  0.40824829],
       [-0.50849656,  0.27343112, -0.81649658],
       [-0.84337993, -0.34934743,  0.40824829]]), array([[-1.66240077e-01,  3.97590898e-01,  2.78127407e-01,
        -2.03573005e-01],
       [-1.72016112e-01,  3.59245145e-01, -3.34428501e-01,
        -2.54169288e-01],
       [-1.77792146e-01,  3.20899391e-01, -1.98179852e-01,
        -1.18100302e-01],
       [-1.83568180e-01,  2.82553637e-01, -6.19312039e-02,
         9.28519069e-01],
       [-1.89344214e-01,  2.44207883e-01,  7.43174447e-02,
        -6.10782770e-02],
       [-1.95120248e-01,  2.05862130e-01,  2.10566093e-01,
        -5.06756227e-02],
       [-2.00896283e-01,  1.67516376e-01,  3.46814742e-01,
        -4.02729683e-02],
       [-2.06672317e-01,  1.2

In [5]:
#------- Tensor Train Decomposition -------

import numpy as np
import tensorly as tl
from tensorly import tt_to_tensor
from tensorly.decomposition import matrix_product_state

tensor = tl.tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                    [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                    [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                    [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

factors2 = matrix_product_state(tensor, rank=[1,2,1])
len(factors)

[f.shape for f in factors]

print(np.round(tt_to_tensor(factors2), decimals=10))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -0. -0. -0.  1.  1.  1.  1. -0.  0.  0.  0.]
 [ 0. -0. -0. -0.  1.  1.  1.  1. -0.  0.  0.  0.]
 [ 0. -0. -0. -0.  1.  1.  1.  1. -0.  0.  0.  0.]
 [-0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -0.]
 [-0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -0.]
 [-0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -0.]
 [-0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -0.]
 [ 0. -0. -0. -0.  1.  1.  1.  1. -0.  0.  0.  0.]
 [ 0. -0. -0. -0.  1.  1.  1.  1. -0.  0.  0.  0.]
 [ 0. -0. -0. -0.  1.  1.  1.  1. -0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
